package amqp

import (
	"context"
	"errors"
	"fmt"
	"runtime/debug"
	"sync"
	"time"
)

// Handler processes a delivery for a [Subscription]. The message is
// acknowledged when the handler returns nil and rejected and requeued when
// it returns an error (or panics), unless the handler acknowledged or
// rejected it itself, e.g. with d.Reject(false) to dead-letter a message
// that can't be processed. ctx is cancelled when the client is closed.
type Handler func(ctx context.Context, d *Delivery) error

// SubscribeOptions are the options for [Queue.Subscribe].
type SubscribeOptions struct {
	// Prefetch is the maximum number of unacknowledged messages, defaults
	// to 20, or twice the number of workers if that's higher.
	Prefetch uint16
	// Workers is the number of goroutines calling the handler, defaults to
	// one, which processes messages in order.
	Workers int
	// NoAck makes the broker consider messages acknowledged when they're
	// delivered, they're lost if the client fails to process them.
	NoAck bool
	// Exclusive requests to be the only consumer of the queue.
	Exclusive bool
	// ConsumerTag identifies the consumer, generated by the broker if empty.
	ConsumerTag string
	// Args are optional arguments, e.g. {"x-stream-offset": "first"}.
	Args Table
}

// Subscription is a consumer that survives reconnects: when the connection
// (or just the consumer's channel) is lost it consumes again as soon as
// possible. Messages that were being processed when the connection was
// lost are redelivered by the broker, so handlers should be idempotent.
type Subscription struct {
	c       *Client
	q       *Queue
	handler Handler
	opts    SubscribeOptions

	mu      sync.Mutex
	cons    *Consumer
	changed chan struct{} // closed when cons is replaced
	stopped bool

	handlerCtx context.Context // the client's context, marked as a handler's

	ctx     context.Context // cancelled to stop the workers
	cancel  context.CancelFunc
	workers sync.WaitGroup
	done    chan struct{}
	err     error
	once    sync.Once
}

func (c *Client) subscribe(ctx context.Context, q *Queue, handler Handler, opts *SubscribeOptions) (*Subscription, error) {
	var o SubscribeOptions
	if opts != nil {
		o = *opts
	}
	o.Workers = max(o.Workers, 1)
	if o.Prefetch == 0 {
		o.Prefetch = uint16(min(max(20, 2*o.Workers), 65535))
	}
	if err := checkShortStr("consumer tag", o.ConsumerTag); err != nil {
		return nil, err
	}
	s := &Subscription{c: c, q: q, handler: handler, opts: o, changed: make(chan struct{}), done: make(chan struct{})}
	s.ctx, s.cancel = context.WithCancel(c.ctx)
	s.handlerCtx = context.WithValue(c.ctx, handlerKey{}, s)

	var cons *Consumer
	for {
		conn, err := c.connection(ctx)
		if err != nil {
			s.cancel()
			return nil, err
		}
		if cons, err = s.consume(ctx, conn); err == nil {
			break
		}
		if !isConnectionLost(err) || ctx.Err() != nil {
			s.cancel()
			return nil, err
		}
	}
	s.cons = cons
	c.topoMu.Lock()
	c.subs[s] = struct{}{}
	c.topoMu.Unlock()
	s.workers.Add(o.Workers)
	for range o.Workers {
		go s.work()
	}
	go s.monitor(cons)
	return s, nil
}

func (s *Subscription) consume(ctx context.Context, conn *Connection) (*Consumer, error) {
	ch, err := conn.Channel(ctx)
	if err != nil {
		return nil, err
	}
	return s.consumeOn(ctx, ch)
}

func (s *Subscription) consumeOn(ctx context.Context, ch *Channel) (*Consumer, error) {
	if !s.opts.NoAck {
		if err := ch.BasicQos(ctx, s.opts.Prefetch, false); err != nil {
			ch.Close()
			return nil, err
		}
	}
	cons, err := ch.BasicConsume(ctx, s.q.Name(), ConsumeOptions{
		Tag:       s.opts.ConsumerTag,
		NoAck:     s.opts.NoAck,
		Exclusive: s.opts.Exclusive,
		Args:      s.opts.Args,
	})
	if err != nil {
		ch.Close()
		return nil, err
	}
	return cons, nil
}

// current returns the active consumer and a channel that's closed when
// it's replaced.
func (s *Subscription) current() (*Consumer, chan struct{}) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.cons, s.changed
}

func (s *Subscription) work() {
	defer s.workers.Done()
	for {
		cons, changed := s.current()
		d, err := cons.Next(s.ctx)
		if s.ctx.Err() != nil {
			return // the message (if any) is requeued when the channel closes
		}
		if err != nil {
			// The consumer stopped, wait for the monitor to replace it
			select {
			case <-changed:
				continue
			case <-s.ctx.Done():
				return
			}
		}
		s.handle(d)
	}
}

func (s *Subscription) handle(d *Delivery) {
	err := s.call(d)
	if err != nil {
		s.c.log.Error("amqp: subscription handler failed", "queue", s.q.Name(), "error", err)
	}
	if s.opts.NoAck || d.Acknowledged() {
		return
	}
	if err == nil {
		err = d.Ack()
	} else {
		err = d.Nack(true)
	}
	if err != nil && !errors.Is(err, ErrClosed) {
		s.c.log.Error("amqp: failed to acknowledge message", "queue", s.q.Name(), "error", err)
	}
}

func (s *Subscription) call(d *Delivery) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("amqp: handler panicked: %v\n%s", r, debug.Stack())
		}
	}()
	return s.handler(s.handlerCtx, d)
}

// monitor consumes again when the consumer stops for any reason other
// than the subscription being cancelled.
func (s *Subscription) monitor(cons *Consumer) {
	for {
		select {
		case <-cons.Done():
		case <-s.ctx.Done():
			return
		}
		if s.ctx.Err() != nil {
			return
		}
		cause := cons.Err()
		if !isConnectionLost(cause) {
			s.c.log.Warn("amqp: consumer stopped, resubscribing", "queue", s.q.Name(), "error", cause)
		}
		redeclared := false
		for {
			var next *Consumer
			var err error
			if !cons.ch.IsClosed() {
				// Cancelled by the broker, consume again on the same channel
				// so that buffered deliveries can still be acknowledged
				next, err = s.consumeOn(s.ctx, cons.ch)
			} else {
				var conn *Connection
				if conn, err = s.c.connection(s.ctx); err != nil {
					s.stop(err, false)
					return
				}
				next, err = s.consume(s.ctx, conn)
			}
			if err == nil {
				cons = next
				s.mu.Lock()
				if s.stopped {
					s.mu.Unlock()
					next.ch.Close()
					return
				}
				s.cons = next
				close(s.changed)
				s.changed = make(chan struct{})
				s.mu.Unlock()
				break
			}
			if s.ctx.Err() != nil {
				return
			}
			if IsCode(err, NotFound) && !redeclared && s.c.managesQueue(s.q) {
				// An auto-delete queue is deleted when its last consumer's
				// channel closes, and an exclusive queue if the broker
				// deleted it, declare it again with its bindings
				redeclared = true
				if err = s.c.redeclareQueue(s.ctx, s.q); err == nil {
					s.c.log.Info("amqp: queue was deleted, redeclared it", "queue", s.q.Name())
					continue
				}
			}
			if !isConnectionLost(err) {
				// E.g. the queue was deleted
				s.c.log.Error("amqp: resubscribing failed, subscription stopped", "queue", s.q.Name(), "error", err)
				s.stop(err, false)
				return
			}
			select {
			case <-time.After(s.c.opts.ReconnectInterval):
			case <-s.ctx.Done():
				return
			}
		}
	}
}

type handlerKey struct{}

// Cancel stops the subscription. It waits for running handlers to return
// (or ctx to be done), messages that weren't processed are requeued. When
// called from the subscription's handler, with the handler's context, it
// doesn't wait for the handlers.
func (s *Subscription) Cancel(ctx context.Context) error {
	return s.stopCtx(ctx, ErrConsumerCancelled, true)
}

func (s *Subscription) stop(reason error, cancelConsumer bool) {
	s.stopCtx(context.Background(), reason, cancelConsumer)
}

func (s *Subscription) stopCtx(ctx context.Context, reason error, cancelConsumer bool) error {
	var err error
	s.once.Do(func() {
		s.cancel()
		s.mu.Lock()
		s.stopped = true
		cons := s.cons
		s.mu.Unlock()
		if cancelConsumer {
			err = cons.Cancel(ctx)
		}
		finish := func() {
			cons.ch.Close() // requeues messages that weren't processed
			s.c.topoMu.Lock()
			delete(s.c.subs, s)
			s.c.topoMu.Unlock()
			s.err = reason
			close(s.done)
		}
		if ctx.Value(handlerKey{}) == s {
			// Called from a handler, which can't wait for itself
			go func() {
				s.workers.Wait()
				finish()
			}()
			return
		}
		waited := make(chan struct{})
		go func() {
			s.workers.Wait()
			close(waited)
		}()
		select {
		case <-waited:
		case <-ctx.Done():
			if err == nil {
				err = ctx.Err()
			}
		}
		finish()
	})
	return err
}

// Done returns a channel that's closed when the subscription stops, either
// because it was cancelled, the client was closed or it couldn't be
// recovered, e.g. because the queue was deleted. Err then tells why.
func (s *Subscription) Done() <-chan struct{} { return s.done }

// Err returns why the subscription stopped, or nil while it's active.
func (s *Subscription) Err() error {
	select {
	case <-s.done:
		return s.err
	default:
		return nil
	}
}

// ConsumerTag returns the tag of the current consumer, it changes when the
// subscription is recovered if the broker generated it.
func (s *Subscription) ConsumerTag() string {
	cons, _ := s.current()
	return cons.Tag()
}

// Queue returns the queue the subscription consumes from.
func (s *Subscription) Queue() *Queue { return s.q }
